name: Toplu Meal Ekle
description: Bir sûre için birden fazla ayeti blok halinde eklemek için kullanın.
title: "[BulkMeal] Sûre {{ inputs.sure }}"
labels: ["meal","bulk"]
body:
  - type: input
    id: sure
    attributes:
      label: Sûre (1-114)
      placeholder: "ör. 3"
    validations:
      required: true
  - type: textarea
    id: block
    attributes:
      label: Toplu Metin
      description: |
        Aşağıdaki biçimlerden biriyle ayetleri ekleyin. Numara + ayraç şart:
        1- İlk ayetin meali...
        2 - İkinci ayetin meali...
        3. Üçüncü ayet ilk cümle...
        Devam satırları numarasız gelebilir ve bir önceki ayete eklenir.
      placeholder: |
        1- ...
        2- ...
        3- ...
    validations:
      required: true
