name: Meal Ekle/Güncelle
description: Bir ayetin meâlini eklemek ya da güncellemek için bu formu kullanın.
title: "[Meal] Sûre {{ inputs.sure }} : Âyet {{ inputs.ayet }}"
labels: ["meal"]
body:
  - type: input
    id: sure
    attributes:
      label: Sûre (1-114)
      placeholder: "ör. 3"
    validations:
      required: true
  - type: input
    id: ayet
    attributes:
      label: Âyet No
      placeholder: "ör. 4"
    validations:
      required: true
  - type: textarea
    id: meal
    attributes:
      label: Meal Metni
      placeholder: "Meâl metnini yazınız..."
    validations:
      required: true
  - type: textarea
    id: aciklama
    attributes:
      label: Açıklama (opsiyonel)
      placeholder: "İç link: [[3:4]] gibi..."
    validations:
      required: false
