name: Moderate Issues
on: { issues: { types: [opened] } }
permissions: { contents: read, issues: write }
jobs:
  close_unallowed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const allowed = new Set(['metinciris']); // ← kendi adın
            const issue = context.payload.issue;
            const author = issue.user.login;
            if (!allowed.has(author)) {
              await github.rest.issues.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                issue_number: issue.number,
                body: "Bu depo yalnız belirli kullanıcıların kayıtlarını işler. Teşekkürler; issue otomatik kapatıldı."
              });
              await github.rest.issues.update({
                owner: context.repo.owner, repo: context.repo.repo,
                issue_number: issue.number, state: "closed", state_reason: "not_planned"
              });
            }
